CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(150) NOT NULL,
  login VARCHAR(85) NOT NULL,
  password VARCHAR(85) NOT NULL,
  firstname VARCHAR(150) NOT NULL,
  lastname VARCHAR(150) NOT NULL,
  born_at DATE NOT NULL,
  address VARCHAR(150) NOT NULL,
  city VARCHAR(150) NOT NULL,
  zip_code CHAR(5) NOT NULL,
  phone CHAR(10) NOT NULL,
  picture  VARCHAR(255)
);

CREATE TABLE sport (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(85) NOT NULL
);

CREATE TABLE activity (
  id INT PRIMARY KEY AUTO_INCREMENT,
  address  VARCHAR(150) NOT NULL,
  city VARCHAR(150) NOT NULL,
  description TEXT,
  zip_code CHAR(5) NOT NULL,
  playing_at DATETIME NOT NULL,
  playing_duration INT NOT NULL,
  nb_places INT NOT NULL,
  auto_validation BOOLEAN NOT NULL,
  price DECIMAL (5,2) DEFAULT 0,
  visibility BOOLEAN NOT NULL,
  user_id INT NOT NULL,
  sport_id INT NOT NULL,
  level ENUM('begginer', 'amateur', 'advance' ,'All') DEFAULT 'All',
  disabled BOOLEAN DEFAULT 0,
  locker BOOLEAN,
  shower BOOLEAN,
  air_conditioning BOOLEAN,
  toilet BOOLEAN,
  FOREIGN KEY (user_id) REFERENCES user(id)
  ON DELETE CASCADE,
  FOREIGN KEY (sport_id) REFERENCES sport(id)
);

CREATE TABLE demand (
  user_id INT NOT NULL, 
  activity_id INT NOT NULL,
  PRIMARY KEY (user_id, activity_id),
  status ENUM('pending', 'accepted', 'refused') NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id)
  ON DELETE CASCADE,
  FOREIGN KEY (activity_id) REFERENCES activity(id)
);

CREATE TABLE participation ( 
  user_id INT NOT NULL, 
  activity_id INT NOT NULL,
  PRIMARY KEY (user_id, activity_id),
  status ENUM('inviting', 'accepted', 'refused') NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id)
  ON DELETE CASCADE,
  FOREIGN KEY (activity_id) REFERENCES activity(id)
);


INSERT INTO sport(name)
VALUES
  ("Football"),
  ("Football association"),
  ("Football américain"),
  ("Football australien"),
  ("Football gaélique"),
  ("Futsal"),
  ("Beach soccer"),
  ("Rugby à XV"),
  ("Rugby à XIII"),
  ("Rugby à 7"),
  ("Touch rugby"),
  ("Flag football"),
  ("Basketball"),
  ("Basketball 3x3"),
  ("Streetball"),
  ("Handball"),
  ("Beach handball"),
  ("Volleyball"),
  ("Beach-volley"),
  ("Snow volleyball"),
  ("Baseball"),
  ("Softball"),
  ("Cricket"),
  ("Cricket T20"),
  ("Hockey sur glace"),
  ("Hockey sur gazon"),
  ("Hockey indoor"),
  ("Roller hockey"),
  ("Bandy"),
  ("Lacrosse"),
  ("Water-polo"),
  ("Netball"),
  ("Kabaddi"),
  ("Sepak takraw"),
  ("Athlétisme"),
  ("Course sur route"),
  ("Cross-country"),
  ("Trail"),
  ("Ultra-trail"),
  ("Marathon"),
  ("Sprint"),
  ("Haies"),
  ("Saut en hauteur"),
  ("Saut en longueur"),
  ("Triple saut"),
  ("Saut à la perche"),
  ("Lancer du poids"),
  ("Lancer du disque"),
  ("Lancer du javelot"),
  ("Lancer du marteau"),
  ("Marche athlétique"),
  ("Natation"),
  ("Natation en eau libre"),
  ("Natation artistique"),
  ("Plongeon"),
  ("Plongeon de haut vol"),
  ("Aquathlon"),
  ("Triathlon"),
  ("Duathlon"),
  ("Pentathlon moderne"),
  ("Cyclisme sur route"),
  ("Cyclisme sur piste"),
  ("Cyclisme sur gravier"),
  ("VTT"),
  ("Enduro VTT"),
  ("Descente VTT"),
  ("BMX race"),
  ("BMX freestyle"),
  ("Cyclo-cross"),
  ("Tennis"),
  ("Tennis de table"),
  ("Badminton"),
  ("Squash"),
  ("Padel"),
  ("Pickleball"),
  ("Racquetball"),
  ("Jeu de paume"),
  ("Pelote basque"),
  ("Golf"),
  ("Mini-golf"),
  ("Disc golf"),
  ("Bowling"),
  ("Billard"),
  ("Snooker"),
  ("Pool"),
  ("Carambole"),
  ("Darts"),
  ("Fléchettes électroniques"),
  ("Pétanque"),
  ("Jeu provençal"),
  ("Boule lyonnaise"),
  ("Quilles"),
  ("Curling"),
  ("Escrime"),
  ("Fleuret"),
  ("Épée"),
  ("Sabre"),
  ("Boxe"),
  ("Boxe anglaise"),
  ("Boxe thaï"),
  ("Kick-boxing"),
  ("Savate"),
  ("MMA"),
  ("Lutte libre"),
  ("Lutte gréco-romaine"),
  ("Lutte celte"),
  ("Judo"),
  ("Karaté"),
  ("Taekwondo"),
  ("Aïkido"),
  ("Kendo"),
  ("Iaido"),
  ("Jiu-jitsu brésilien"),
  ("Sambo"),
  ("Hapkido"),
  ("Sumo"),
  ("Pankration"),
  ("Muay boran"),
  ("Wrestling professionnel"),
  ("Formule 1"),
  ("Formule 2"),
  ("Formule 3"),
  ("Formule E"),
  ("Rallye"),
  ("Rallycross"),
  ("Endurance automobile"),
  ("Karting"),
  ("MotoGP"),
  ("Moto2"),
  ("Moto3"),
  ("Superbike"),
  ("Motocross"),
  ("Supercross"),
  ("Enduro moto"),
  ("Trial moto"),
  ("Speedway"),
  ("NASCAR"),
  ("Drag racing"),
  ("Drift"),
  ("Off-road"),
  ("Aviron"),
  ("Canoë"),
  ("Kayak"),
  ("Canoë slalom"),
  ("Kayak de mer"),
  ("Rafting"),
  ("Voile"),
  ("Planche à voile"),
  ("Kitesurf"),
  ("Wingfoil"),
  ("Surf"),
  ("Bodyboard"),
  ("Longboard surf"),
  ("Stand up paddle"),
  ("Ski nautique"),
  ("Wakeboard"),
  ("Wakesurf"),
  ("Plongée sous-marine"),
  ("Apnée"),
  ("Pêche sportive"),
  ("Chasse sous-marine"),
  ("Ski alpin"),
  ("Ski de fond"),
  ("Ski freestyle"),
  ("Ski de bosses"),
  ("Ski de randonnée"),
  ("Snowboard"),
  ("Snowboard freestyle"),
  ("Biathlon"),
  ("Saut à ski"),
  ("Combiné nordique"),
  ("Bobsleigh"),
  ("Skeleton"),
  ("Luge"),
  ("Patinage artistique"),
  ("Patinage de vitesse"),
  ("Short-track"),
  ("Escalade sportive"),
  ("Bloc"),
  ("Escalade de difficulté"),
  ("Escalade de vitesse"),
  ("Alpinisme"),
  ("Via ferrata"),
  ("Randonnée sportive"),
  ("Course d'orientation"),
  ("Raid multisports"),
  ("Parkour"),
  ("Free running"),
  ("Skateboard"),
  ("Longboard"),
  ("Roller"),
  ("Roller freestyle"),
  ("Roller derby"),
  ("Trottinette freestyle"),
  ("Trottinette électrique sportive"),
  ("Parachutisme"),
  ("Parapente"),
  ("Deltaplane"),
  ("Wingsuit"),
  ("Vol à voile"),
  ("Montgolfière"),
  ("Drone racing"),
  ("Échecs"),
  ("Go"),
  ("Dames"),
  ("Bridge"),
  ("Poker sportif"),
  ("Mah-jong"),
  ("Scrabble compétitif"),
  ("Esport"),
  ("Sim racing"),
  ("Speedcubing")
